services:
  - type: web
    name: howerobinsonbunkerprices
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    plan: free
    envVars:
      - key: LOCAL_WORKBOOK_ROOT
        value: /opt/render/project/src/render_excel_files
